version: "3.9"

services:

  mongo_db:
    container_name: mongoContainer
    image: mongo:latest
    restart: on-failure
    volumes:
      - mongo_db://data/db
    ports:
      - 27017:27017

  api:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: mission_six_db
      NAME: Vin
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
